// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjuNl_Hjcpc8YbIX9TlsvV02QRpTk9YEU',
    appId: '1:683953339164:web:6d8fc87c195b085ebf58d9',
    messagingSenderId: '683953339164',
    projectId: 'mindfulwalk-77713',
    authDomain: 'mindfulwalk-77713.firebaseapp.com',
    storageBucket: 'mindfulwalk-77713.appspot.com',
    measurementId: 'G-ZBXGNQL4D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1rRUXar5GxX5s1AaT_k47NeyNY9rMtQ',
    appId: '1:683953339164:android:95b43a4327283acbbf58d9',
    messagingSenderId: '683953339164',
    projectId: 'mindfulwalk-77713',
    storageBucket: 'mindfulwalk-77713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-SWnw001xCfL_ge7JNo9QqW5kM3zUeXI',
    appId: '1:683953339164:ios:8bf77318c400ae0cbf58d9',
    messagingSenderId: '683953339164',
    projectId: 'mindfulwalk-77713',
    storageBucket: 'mindfulwalk-77713.appspot.com',
    iosBundleId: 'com.example.mindfulwalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-SWnw001xCfL_ge7JNo9QqW5kM3zUeXI',
    appId: '1:683953339164:ios:8bf77318c400ae0cbf58d9',
    messagingSenderId: '683953339164',
    projectId: 'mindfulwalk-77713',
    storageBucket: 'mindfulwalk-77713.appspot.com',
    iosBundleId: 'com.example.mindfulwalk',
  );
}
